### ISSUE TITLE
where is the train.txt  to run 

### ISSUE THREAD

**Issue by andyyuan78** [dansoutner/LSTM#2]
ubgpu@ubgpu:~/github/LSTM$ python lstm.py --train train.txt dev.txt test.txt --hidden 100 --save-net example.lstm-lm
LSTM LM version 0.6.2
File train.txt not found.
File dev.txt not found.
File test.txt not found.
Traceback (most recent call last):
  File "lstm.py", line 114, in <module>
    l = LSTM.LSTM(args)
  File "/home/ubgpu/github/LSTM/LSTM.py", line 166, in __init__
    self.dic = self.create_dic(self.train_file)
  File "/home/ubgpu/github/LSTM/LSTM.py", line 336, in create_dic
    sentences = (line.split() for line in codecs.open(text_file, "r", ENCODING))
  File "/usr/lib/python2.7/codecs.py", line 878, in open
    file = __builtin__.open(filename, mode, buffering)
IOError: [Errno 2] No such file or directory: 'train.txt'
ubgpu@ubgpu:~/github/LSTM$ git pull
Already up-to-date.
ubgpu@ubgpu:~/github/LSTM$

**Comment by dansoutner** [comment]
Text files are not part of the repo. Use any text e.g. PTB from http://www.fit.vutbr.cz/~imikolov/rnnlm/simple-examples.tgz
